### ISSUE TITLE
Add background image

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#11]
The current background image is plain -- could it be spruced up to reflect the actual weather? clouds floating in the background? or just look nicer in general?

This is an open-ended issue and creativity is welcome.

  ![screenshot of the flask weather app](https://raw.githubusercontent.com/M0nica/flask_weather/master/static/nyc_weather_screenshot.png)

**Comment by puneetns** [comment]
from Tkinter import *
from PIL import ImageTk,Image

... other stuffs

root=Tk()
canvasWidth=600
canvasHeight=400
self.canvas=Canvas(root,width=canvasWidth,height=canvasHeight)
backgroundImage=root.PhotoImage("D:\Documents\Background.png")
backgroundLabel=root.Label(parent,image=backgroundImage)
backgroundLabel.place(x=0,y=0,relWidth=1,relHeight=1)
self.canvas.pack()
root.mainloop()

**Comment by hacky1997** [comment]
can i try? if u have no problem!

**Comment by NahidRM** [comment]
Yeah, I think it'd be pretty cool if it reflected the actual weather. I have that feature on my Gmail and it's really nice, specially those days where I've spent my entire time inside.

**Comment by AbhiAgarwal192** [comment]
@M0nica Currently i only see forecast for rain.
