### ISSUE TITLE
Add Weather Commentary [Submit copy!]

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#14]
Currently, we display `rain_commentary` based on the `RAIN_WARNING`. It would be great if additional commentary was added to look at `RAIN_WARNING`, `temperature` and maybe `weather_icon`.

Creative but relevant copy enhancements are welcome! This is something that multiple people can contribute to.

Also at some point, it could be implemented so that the message varies when you refresh the page with another relevant piece of commentary for the same weather report.

   ``` if RAIN_WARNING == 0:
        rain_commentary = "there is a no chance of rain! It's a sunny day"
    elif 0 < RAIN_WARNING <= .5:
        rain_commentary = "there is a slight chance of rain. You might want to grab an umbrella"
    elif  .5 < RAIN_WARNING <.75:
        rain_commentary = "there is a high chance of rain. Grab an umbrella on your way out!"
    elif  RAIN_WARNING == 1:
        rain_commentary = "it is raining right now!"
    else:
        rain_commentary = "it is definitely going to rain today! GRAB YOUR UMBRELLA."
```

**Comment by blitzh0t** [comment]
let me try...

**Comment by M0nica** [comment]
Thanks @blitzh0t and @rushilShetty
