### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#24]
It would be great to add a linter to this project to keep the styling uniform as this project grows. http://flake8.pycqa.org/en/latest/.

@psyonara did some lint formatting work in https://github.com/M0nica/flask_weather/pull/23

**Comment by psyonara** [comment]
I'll tackle this if you don't mind. :)

**Comment by M0nica** [comment]
Great! Thank you @psyonara.

**Comment by psyonara** [comment]
And I assume we can delete ```detect_location_weather.py```, since it seems to be an old version of ```app.py```?

**Comment by psyonara** [comment]
@M0nica Have submitted the PR, let me know if you want anything done differently.

**Comment by M0nica** [comment]
Thanks @psyonara. I created a follow-up ticket for someone to add instructions for using the linter. https://github.com/M0nica/flask_weather/issues/44

I am not sure if we want to force a pre-commit check. I was having trouble running flake8 in VSCode and ended up having to just type flake8 in the command line but not sure if I was missing a step.
