### ISSUE TITLE
[DISCUSSION] Renaming App

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#30]
I am planning on having this app hosted on Heroku or Digital Ocean https://github.com/M0nica/flask_weather/issues/29

However, I think the app needs a new name off of Github (and additional branding i.e., header once a name is decided).

Does anyone have thoughts as to what the name could be?

In terms of development work, there will be follow up tasks to update the website (once a name is determined)
- adding name to header
- adding name to title
- adding name to footer
- updating documentation as needed
...etc.

**Comment by vinay72** [comment]
Title should be like : Weather App.

**Comment by jeasoft** [comment]
Clima (weather in Spanish). it's simple and and short XD

**Comment by thesohelshaikh** [comment]
Clima - WeatherApp

**Comment by n8sworkspace** [comment]
Copyright and or ownership disclaimer on footer of page. Best of luck and happy Hacktoberfest

**Comment by M0nica** [comment]
Thanks! Decided to go with Clima @jeasoft @thesohelshaikh https://clima-weather.herokuapp.com/
