### ISSUE TITLE
Allow users to toggle between Celsius and Fahrenheit

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#34]
The functionality for developers to choose temperature unit was introduced in this PR: https://github.com/M0nica/flask_weather/pull/32. Add the ability for users to switch to celsius or fahrenheit depending on which one is displayed.

**Comment by alessandrojcm** [comment]
I'll work on this.

**Comment by RiotPharaoh** [comment]
Hello, I can help you with your issue in few minutes, if you interested.

**Comment by neequole** [comment]
@M0nica I'll happy to work on this. If the user toggle the temperature unit does it also change the setting on the config file?
