### ISSUE TITLE
Display temperature unit °C or °F

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#35]
Display °C or °F after temperature depending on which unit is being used.

View this PR for more context about how temperature units are currently being used in the app: 

https://github.com/M0nica/flask_weather/pull/32

**Comment by jr7square** [comment]
I can pick this up!

**Comment by satish605** [comment]
celsius = 37.5
# calculate fahrenheit
fahrenheit = (celsius * 1.8) + 32
print('%0.1f degree Celsius is equal to %0.1f degree Fahrenheit' %(celsius,fahrenheit))

**Comment by RiotPharaoh** [comment]
I'll do it in few minutes, If you are interested.
