### ISSUE TITLE
replace ipgetter with another python package to get external IP address

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#4]
ipgetter is a utility to fetch your external IP address. It appears to be deprecated. It would be great for someone to find a suitable replacement and update.

**Comment by felubra** [comment]
Can I use a external service to determine the IP?

**Comment by byarmis** [comment]
I'm interested in working on this

**Comment by M0nica** [comment]
Awesome, let me know if you need anything from me @byarmis

**Comment by byarmis** [comment]
@M0nica Thanks, think I'm good!

**Comment by M0nica** [comment]
Thank you!
