### ISSUE TITLE
Migrate Front End to React

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#45]
Want to switch from using plain HTML to using React for the front-end and continue using Python/Flask to handle the logic. 

Depending on the approach this can/should be broken up into smaller tasks.

Related links:
- https://github.com/keredson/bottle-react
- https://realpython.com/the-ultimate-flask-front-end/

**Comment by nickisaacs** [comment]
@M0nica 
Can I pick this up?

**Comment by M0nica** [comment]
Sure that would be great @nickisaacs. Do you have any ideas for minimizing merge conflicts?

**Comment by nickisaacs** [comment]
@M0nica Do you have any existing merge conflicts?

**Comment by nickisaacs** [comment]
@M0nica 
I wouldn't be working on the HTML. I'm creating a react application inside your project, and I will convert the python app to a pure API which will be consumed by the React application. So now you will need to start the python app, and run the react app as well.

**Comment by nickisaacs** [comment]
https://github.com/M0nica/flask_weather/pull/49 @M0nica
