### ISSUE TITLE
Add Header

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#59]
The app should have a header that says: Clima Weather

https://clima-weather.herokuapp.com/

**Comment by josephdrane** [comment]
@M0nica I am a first timer, so I am going to give this a shot!

**Comment by AbhiAgarwal192** [comment]
Do you mean instead of "Local Weather for ****" , the header should be "Clima Weather"

**Comment by 2hands10fingers** [comment]
I'm on it

**Comment by ehx** [comment]
i take it

**Comment by ehx** [comment]
i take it

**Comment by elsonlim** [comment]
Github servers were down; so I didn't see all these comments. Have already created a PR for this issue though.

**Comment by AbhiAgarwal192** [comment]
Created a pull request for the same.

**Comment by beckyw5** [comment]
Is this still open?

**Comment by anushkajj** [comment]
Can I still work on this?
