### ISSUE TITLE
Allow users to manually choose another city

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#65]
- If you visit website and then go to a new city the session cookie may still be present (if you haven't closed browser) and will display weather information for previous city
- add a link for someone to click on if they want to see the weather in another city i.e. (Want to see the weather for another city?)
- when the user clicks they should be able to change the city -- you can decide what type of UI to use to allow user to choose a different city

**Comment by marataziat** [comment]
Can I take that pls :3

**Comment by ChrisVo** [comment]
Hi, I can help with this!

**Comment by gracemshea** [comment]
I can work on this!

**Comment by rods-honorio** [comment]
i'd like to try :D
