### ISSUE TITLE
Dark Sky has joined Apple.

### ISSUE THREAD

**Issue by bijanfallah** [M0nica/flask_weather#87]
type:bug 
It is not possible to sign up in dark sky : 
https://blog.darksky.net

Today we have some important and exciting news to share: Dark Sky has joined Apple.

**Comment by M0nica** [comment]
Thanks for flagging this @bijanfallah.  Do you have any recommendations for other APIs?

**Comment by bijanfallah** [comment]
ur welcome, sorry I have no recommendations :(
