### ISSUE TITLE
Update Color of Icon (or add emojis) To Reflect Weather

### ISSUE THREAD

**Issue by M0nica** [M0nica/flask_weather#9]
We display weather icons with the weather. Some enhancements could be made to change the color of the icon to correlate with the weather (sunny i.e., orange/yellow; rain blue; snow/sleet, etc. grey).

OR display emojis instead of current weather icons

Note the types of icon text values that our current weather API returns
> A machine-readable text summary of this data point, suitable for selecting an icon for display. If defined, this property will have one of the following values: clear-day, clear-night, rain, snow, sleet, wind, fog, cloudy, partly-cloudy-day, or partly-cloudy-night. (Developers should ensure that a sensible default is defined, as additional values, such as hail, thunderstorm, or tornado, may be defined in the future.)

We currently handle the following:
``` {% if weather_icon == "clear-day" %}
   <i class="wi wi-day-sunny"></i>
{% elif weather_icon == "clear-night"%}
   <i class="wi wi-night-clear"></i>
{% elif weather_icon == "rain"%}
    <i class="wi wi-rain"></i>
{% elif weather_icon == "snow"%}
    <i class="wi wi-snow"></i>
{% elif weather_icon == "sleet"%}
    <i class="wi wi-sleet"></i>
{% elif weather_icon == "wind"%}
    <i class="wi wi-wind"></i>
{% elif weather_icon == "fog"%}
    <i class="wi wi-fog"></i>
{% elif weather_icon == "cloudy"%}
    <i class="wi wi-cloudy"></i>
{% elif weather_icon == "partly-cloudy-day"%}
    <i class="wi wi-forecast-io-partly-cloudy-day"></i>
{% elif weather_icon == "partly-cloudy-day"%}
    <i class="wi wi-forecast-io-partly-cloudy-day"></i>
{% else %}
    <i class="wi wi-day-sunny"></i>

 {% endif %}
```

  ![screenshot of the flask weather app](https://raw.githubusercontent.com/M0nica/flask_weather/master/static/nyc_weather_screenshot.png)

**Comment by webhaikal** [comment]
Will be claiming this for Hacktoberfest if no one else is doing it.

**Comment by M0nica** [comment]
okay, great @webhaikal. Do you know which approach you are going to take?

**Comment by webhaikal** [comment]
For now just gonna give it a few colors for now. Are you planning on having
it live updating the weather?

**Comment by M0nica** [comment]
@webhaikal currently the weather data only updates when the weather changes

**Comment by webhaikal** [comment]
So it updates automatically or we need to refresh the page?

**Comment by M0nica** [comment]
@webhaikal You need to refresh the page to see new weather updates -- although for this issue you may need to hard-code the icons to test out how they visually look as when you refresh it should have the same/similar weather info and you won't see the full range of weather icons in one session otherwise

**Comment by anushkajj** [comment]
Can I take this issue if no one is working on it?
